# Generated by Django 5.0.1 on 2024-02-03 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='description',
            new_name='storyline',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplatform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
