# Generated by Django 5.0.1 on 2024-02-08 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0007_watchlist_abg_rating_watchlist_number_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="abg_rating",
            new_name="avg_rating",
        ),
    ]
